{
 "title": "BMW Connected Drive",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"font-size:60px;text-align=center\">BMW X1 xDrive25e</h1>         "
   }
  },
  {
   "title": "Door lock state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bmwcd_door_lock_state" }
   ]
  },
  {
   "title": "Door driver - front",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bmwcd_door_driver_front_state" }
   ]
  },
  {
   "title": "Door driver - rear",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bmwcd_door_driver_rear_state" }
   ]
  },
  {
   "title": "Vehicle check due date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmwcd_vehicle_check_cbs_due_date * 1000"
    }
   ]
  },
  {
   "title": "Charge level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bmwcd_charge_level", "legendFormat": "Charge level" }
   ]
  },
  {
   "title": "Door passenger - front",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmwcd_door_passenger_front_state"
    }
   ]
  },
  {
   "title": "Door passenger - rear",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmwcd_door_passenger_rear_state"
    }
   ]
  },
  {
   "title": "Vehicle check in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmwcd_vehicle_check_cbs_remaining_mileage"
    }
   ]
  },
  {
   "title": "Hood",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bmwcd_hood_state" }
   ]
  },
  {
   "title": "Trunk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bmwcd_trunk_state" }
   ]
  },
  {
   "title": "Oil service due date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmwcd_oil_check_cbs_due_date * 1000"
    }
   ]
  },
  {
   "title": "Mileage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bmwcd_mileage", "legendFormat": "Mileage" }
   ]
  },
  {
   "title": "Remaining range - Electric",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bmwcd_remaining_electric_range", "legendFormat": "Hybrid range" }
   ]
  },
  {
   "title": "Remaining range - Hybrid",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bmwcd_remaining_hybrid_range", "legendFormat": "Hybrid range" }
   ]
  },
  {
   "title": "Oil service in",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "km" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmwcd_oil_cbs_remaining_mileage"
    }
   ]
  },
  {
   "title": "Brake fluid check due date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bmwcd_brake_fluid_check_cbs_due_date * 1000"
    }
   ]
  },
  {
   "title": "Charging status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "bmwcd_charging_status", "legendFormat": "Charging status" }
   ]
  },
  {
   "title": "Cable connection",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "bmwcd_connection_status", "legendFormat": "Cable connection" }
   ]
  },
  {
   "title": "Remaining range - Electric",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "lengthkm" }
   ],
   "targets": [
    { "expr": "bmwcd_remaining_electric_range", "legendFormat": "Remaining range - Electric" }
   ]
  },
  {
   "title": "Remaining range - Hybrid",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "lengthkm" }
   ],
   "targets": [
    { "expr": "bmwcd_remaining_hybrid_range", "legendFormat": "Remaining range - Hybrid" }
   ]
  },
  {
   "title": "Mileage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "km" }
   ],
   "targets": [
    { "expr": "bmwcd_mileage", "legendFormat": "Mileage" }
   ]
  },
  {
   "title": "Charge level",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "bmwcd_charge_level", "legendFormat": "Charge level" }
   ]
  }
 ]
}